config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dancers#index'
  resources :dancers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dancer.rb
class Dancer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dancers_controller.rb
class DancersController < ApplicationController
  def index
    @dancers = Dancer.all
  end

  def new
    @dancer = Dancer.new
  end

  def create
    Dancer.create(dancer_params)
    redirect_to root_path
  end

  private

  def dancer_params
    params.require(:dancer).permit(:name, :bio, :style)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dancer_helper.rb
module DancerHelper
end

app/helpers/dancers_helper.rb
module DancersHelper
end

app/views/dancers/index.html.erb
<% @dancers.each do |dancer| %>
  <div class="boxing col-10 offset-1">
    <h1><%= dancer.name %></h1>
    <i><%= dancer.bio %></i><br /><br />
    <p>-Dance Style: <%= dancer.style %></p><br />
  </div>
<% end %>

app/views/dancers/new.html.erb
<div class="boxing col-10 offset-1">
  <h1>Enter new Dancer's info</h1>
  <%= simple_form_for @dancer do |f| %>
    <%= f.input :name %>
    <%= f.input :bio %>
    <%= f.input :style %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>      
      <%= link_to 'World of Dance', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to 'New Dancer', new_dancer_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>